sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t ngedemer/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true ngedemer/react-test npm test

after_success:
  - docker build -t ngedemer/multi-client ./client
  - docker build -t ngedemer/multi-nginx ./nginx
  - docker build -t ngedemer/multi-server ./server
  - docker build -t ngedemer/multi-worker ./worker

#login to docker cli
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
# take images and push to docker hub
  - docker push ngedemer/multi-client
  - docker push ngedemer/multi-nginx
  - docker push ngedemer/multi-server
  - docker push ngedemer/multi-worker